### ISSUE TITLE
Tautulli Docker Support?

### ISSUE THREAD

**Issue by Tharic99** [airship-david/Trailer-Downloader#29] opened 2019-06-20 21:00 UTC
I'm curious if you have any ideas how to get this working when running Tautulli in a docker image. 

Being a docker container, it doesn't have the requirements installed already, so installing them would be needed but of course then every time the container is updated that has to occur again, etc. 

Any ideas or is this just not possible with the standard Tautulli docker container?

**Comment by airship-david** [comment] 2019-06-20 21:04
No idea but a new issue shouldn't have been opened for this since you're not actually referencing any problem with the script. 3 people are consistently creating issues and nobody else is. Closing this for now. Feel free to get this working and then tell everyone else how you did it.

**Closed by airship-david** 2019-06-20 21:04 UTC

**Comment by danz0l** [comment] 2019-06-21 06:52
I think the issue is that github doesn't give a forum to projects to discuss things regards the project.

The only way to give any feedback, ask for help for others to solve or to solve things for the good of the community using it is to open issues users are having or to offer feedback in the direction of the script.

Nobody means anything by it, and it's healthy to have a community that is generally interested in helping to improve an already excellent script.

Or am i missing a point here ?

**Comment by airship-david** [comment] 2019-06-21 18:28
Sorry if that sounded harsh guys. I totally agree on the issue with there being no forum for basic discussions. That is an issue that pretty much all of GitHub can agree on.

**Comment by airship-david** [comment] 2019-06-21 18:30
Part of my frustration here pertains to the same user having opened another issue a few minutes prior to this one and my inbox getting clogged up before I even had a chance to address the previous one. Let's please try to keep things concise. Thanks!

**Comment by airship-david** [comment] 2019-06-21 18:49
Please use issue #31 (General Discussions) for topics such as this one. That should solve the issue going forward.
